apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  generation: 1
  managedFields:
    - apiVersion: cert-manager.io/v1
      fieldsType: FieldsV1
      manager: controller
      operation: Update
  name: the-hub-cert
  namespace: default
spec:
  dnsNames:
    - hub.rocketseat.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: the-hub-tls